on: 
  push:
    branches:
      - v2
      
name: phpunit
jobs:
  phpunit:
    runs-on: ubuntu-latest
   # container:
   #   image: kirschbaumdevelopment/laravel-test-runner:7.3

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ninja
          MYSQL_DATABASE: ninja
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v1
      with:
        ref: v2
        fetch-depth: 1

    - name: Install composer dependencies
      run: |
        composer install

    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate
        php artisan optimize
        
    - name: Prepare JS/CSS assets
      run: |
        npm i
        npm run production
          
    - name: Migrate Database
      run: |
        php artisan migrate:fresh --seed --force && php artisan db:seed --class=RandomDataSeeder --force

    - name: Run Testsuite
      run: vendor/bin/phpunit --testdox
